image: registry.gitlab.com/harag/sbcl-docker-gitlab-ci

stages:
  - test

before_script:
  - cd ~/src
  - git clone https://gitlab-ci-token:$CI_JOB_TOKEN@gitlab.com/Harag/cl-naive-tests.git

test:
  stage: test
  script:
     - make -C cl-naive-tests test DEPENDENCYDIR=~/src

  artifacts:
    reports:
      junit: /root/src/junit-results.xml
