image: registry.gitlab.com/harag/sbcl-docker-gitlab-ci

stages:
  - test

before_script:
  - echo "Hi!"

test:
  stage: test
  script:
     - make -C cl-naive-tests test "DEPENDENCYDIR=${CI_PROJECT_DIR}/../"

  artifacts:
    reports:
      junit: junit-results.xml
