image: registry.gitlab.com/harag/sbcl-docker-gitlab-ci

stages:
  - test

before_script:
  - echo "Hi!"

test:
  stage: test
  script:
      - make test "DEPENDENCYDIR=${CI_PROJECT_DIR}/../"

  artifacts:
    paths:
      - tests/tests.lisp
    reports:
      junit: tests/artifacts/junit-results.xml

