image: registry.gitlab.com/harag/sbcl-docker-gitlab-ci

stages:
  - test

before_script:
  - cd ~/src
  - git clone -b "$CI_COMMIT_BRANCH" https://gitlab-ci-token:$CI_JOB_TOKEN@gitlab.com/Harag/cl-naive-tests.git

test:
  stage: test
  script:
     - make test DEPENDENCYDIR=~/src ARTDIR=$CI_PROJECT_DIR/

  artifacts:
    reports:
      junit: junit-results.xml
